# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

parameters:
- name: succeed
  displayName: Succeed
  type: boolean
  default: true

trigger:
  branches:
    include:
      - master
      - release/*
    exclude:
      - release/version-0.1
  paths:
    include: 
      - wwwroot
pr:

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

jobs:
- job: Build
  steps:
  - script: echo "building..."
    displayName: "Echo Building"
  - script: |
      echo "will fail"
      exit 1
    displayName: "If Succed Parameter"
    condition: eq(${{ parameters.succeed}}, false)
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

- job: ErrorHandler
  dependsOn: Build
  condition: failed()
  steps: 
  - bash: |
      az boards work-item create \
        --title "Build $(build.buildNumber) failed" \
        --type issue \
        --org $(System.TeamFoundationCollectionUri) \
        --project $(System.TeamProject)
    env: 
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
    displayName: 'Create work item on failure'